openapi: 3.1.0
info:
  title: OCPI 2.1.1 - Shared CDR Classes
  version: 2.1.1
paths: {}
components:
  schemas:
    ChargingPeriod:
      type: object
      description: A Charging Period is a group of dimension values for a period of
        time during a charging session.
      required:
        - start_date_time
        - dimensions
      properties:
        start_date_time:
          $ref: ./types.yaml#/components/schemas/DateTime
        dimensions:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/CdrDimension"
          description: List of relevant values for this charging period.
      additionalProperties: true
    CdrDimension:
      type: object
      description: A measured dimension value for a charging period.
      required:
        - type
        - volume
      properties:
        type:
          $ref: "#/components/schemas/CdrDimensionType"
        volume:
          type: number
          description: Volume of the dimension consumed, measured according to the
            dimension type.
      additionalProperties: true
    AuthMethod:
      type: string
      enum:
        - AUTH_REQUEST
        - WHITELIST
      description: Method used to authenticate a charging session.
    CdrDimensionType:
      type: string
      enum:
        - ENERGY
        - FLAT
        - MAX_CURRENT
        - MIN_CURRENT
        - PARKING_TIME
        - TIME
      description: Types of CDR dimensions.
