openapi: 3.1.0
info:
  title: OCPI 2.1.1 - Shared CDR Classes
  version: 2.1.1
  license:
    name: Creative Commons Attribution-NoDerivatives 4.0 International
    url: https://creativecommons.org/licenses/by-nd/4.0/
paths: {}
components:
  schemas:
    ChargingPeriod:
      type: object
      description: >-
        A charging period consists of a start timestamp and a list of possible
        values that influence this period, for example: Amount of energy charged
        this period, maximum current during this period etc.
      required:
        - start_date_time
        - dimensions
      properties:
        start_date_time:
          $ref: ./types.yaml#/components/schemas/DateTime
        dimensions:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/CdrDimension"
          description: List of relevant values for this charging period.
      additionalProperties: true
    CdrDimension:
      type: object
      description: A measured dimension value for a charging period.
      required:
        - type
        - volume
      properties:
        type:
          $ref: "#/components/schemas/CdrDimensionType"
        volume:
          type: number
          description: Volume of the dimension consumed, measured according to the
            dimension type.
      additionalProperties: true
    AuthMethod:
      type: string
      enum:
        - AUTH_REQUEST
        - WHITELIST
      x-enumDescriptions:
        AUTH_REQUEST: Authentication request from the eMSP
        WHITELIST: Whitelist used to authenticate, no request done to the eMSP
      description: Method used to authenticate a charging session.
    CdrDimensionType:
      type: string
      enum:
        - ENERGY
        - FLAT
        - MAX_CURRENT
        - MIN_CURRENT
        - PARKING_TIME
        - TIME
      x-enumDescriptions:
        ENERGY: defined in kWh, default step_size is 1 Wh
        FLAT: flat fee, no unit
        MAX_CURRENT: defined in A (Ampere), Maximum current reached during charging session
        MIN_CURRENT: defined in A (Ampere), Minimum current used during charging session
        PARKING_TIME: "time not charging: defined in hours, default step_size is 1 second"
        TIME: "time charging: defined in hours, default step_size is 1 second"
      description: Types of CDR dimensions.
