openapi: 3.1.0
info:
  title: OCPI 2.1.1 - Shared Token Classes
  version: 2.1.1
paths: {}
components:
  schemas:
    LocationReferences:
      type: object
      description: References to location details.
      required:
        - location_id
      properties:
        location_id:
          type: string
          maxLength: 39
          description: Unique identifier for the location.
        evse_uids:
          type: array
          items:
            type: string
            maxLength: 39
          description: Unique identifiers for EVSEs within the CPO's platform for the
            EVSEs within the given location.
        connector_ids:
          type: array
          items:
            type: string
            maxLength: 36
          description: Identifies the connectors within the given EVSEs.
      additionalProperties: true
    TokenType:
      anyOf:
        - type: string
          enum:
            - OTHER
            - RFID
        - type: string
      description: Type of charging token.
    WhitelistType:
      type: string
      enum:
        - ALWAYS
        - ALLOWED
        - ALLOWED_OFFLINE
        - NEVER
      description: Defines the whitelist behavior for a Token.
    AllowedType:
      type: string
      enum:
        - ALLOWED
        - BLOCKED
        - EXPIRED
        - NO_CREDIT
        - NOT_ALLOWED
      description: Authorization status of a Token.
