openapi: 3.1.0
info:
  title: OCPI 2.1.1 - Shared Token Classes
  version: 2.1.1
  license:
    name: Creative Commons Attribution-NoDerivatives 4.0 International
    url: https://creativecommons.org/licenses/by-nd/4.0/
paths: {}
components:
  schemas:
    LocationReferences:
      type: object
      description: References to location details.
      required:
        - location_id
      properties:
        location_id:
          type: string
          maxLength: 39
          description: Unique identifier for the location.
        evse_uids:
          type: array
          items:
            type: string
            maxLength: 39
          description: Unique identifiers for EVSEs within the CPO's platform for the
            EVSEs within the given location.
        connector_ids:
          type: array
          items:
            type: string
            maxLength: 36
          description: Identifies the connectors within the given EVSEs.
      additionalProperties: true
    TokenType:
      type: string
      enum:
        - OTHER
        - RFID
      x-enumDescriptions:
        OTHER: Other type of token
        RFID: RFID Token
      description: Type of charging token.
    WhitelistType:
      type: string
      enum:
        - ALWAYS
        - ALLOWED
        - ALLOWED_OFFLINE
        - NEVER
      x-enumDescriptions:
        ALWAYS: Token always has to be whitelisted, realtime authorization is not possible/allowed.
        ALLOWED: It is allowed to whitelist the token, realtime authorization is also allowed.
        ALLOWED_OFFLINE: Whitelisting is only allowed when CPO cannot reach the eMSP (communication between CPO and eMSP is offline)
        NEVER: Whitelisting is forbidden, only realtime authorization is allowed. Token should always be authorized by the eMSP.
      description: Defines the whitelist behavior for a Token.
    AllowedType:
      type: string
      enum:
        - ALLOWED
        - BLOCKED
        - EXPIRED
        - NO_CREDIT
        - NOT_ALLOWED
      x-enumDescriptions:
        ALLOWED: This Token is allowed to charge at this location.
        BLOCKED: This Token is blocked.
        EXPIRED: This Token has expired.
        NO_CREDIT: This Token belongs to an account that has not enough credits to charge at the given location.
        NOT_ALLOWED: Token is valid, but is not allowed to charge at the given location.
      description: Authorization status of a Token.
